info:
  name: teambuiltingstatistic
  description: Team Builting Statistics

server:
  port: ${PORT:8081}

spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      org.hibernate.envers.store_data_at_delete: true
      org.hibernate.envers.global_with_modified_flag: true
      org.hibernate.envers.track_entities_changed_in_revision: true
  datasource:
    initialize: false
    url: jdbc:mysql://mysql:3306/statisticdb?createDatabaseIfNotExist=true
    username: root
    password:
    hikari:
      minimumIdle: 20
      maximumPoolSize: 30
      idleTimeout: 10000
      driverClassName: com.mysql.jdbc.Driver
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jackson:
    serialization:
      write-dates-with-zone-id: false
    deserialization:
      accept-float-as-int: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  rabbitmq:
    url: amqp://uzoukkav:xN719DwSB64TPZ5dbclQ12LJ0o7lZ2tU@spotted-monkey.rmq.cloudamqp.com/uzoukkav


---

# Queue configuration
messaging:
  event.amqp:
    exchange: teambuilting.ex
    queue: team.queue
    team-crud-routing-key: team.crud
    player-crud-routing-key: player.crud

---

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/statisticChangeset.xml
  contexts: default

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/statisticdb?createDatabaseIfNotExist=true
    username: root
    password: root
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672