info:
  name: teambuiltingstatistic
  description: Team Builting Statistics

server:
  port: ${PORT:8081}

spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      org.hibernate.envers.store_data_at_delete: true
      org.hibernate.envers.global_with_modified_flag: true
      org.hibernate.envers.track_entities_changed_in_revision: true
  datasource:
    initialize: false
    url: jdbc:h2:mem:testDB;MODE=Mysql;DATABASE_TO_UPPER=false
    username: root
    password:
    hikari:
      driverClassName: org.h2.Driver
  jackson:
    serialization:
      write-dates-with-zone-id: false
    deserialization:
      accept-float-as-int: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ


---

# Queue configuration
messaging:
  amqp:
    team:
      exchange:
        name: TEAMBUILTING.E.TEAM
        durable: true
        autodelete: false
      queue:
        name: TEAMBUILTING.Q.STATISTIC.TEAM
        binding: team.#
        durable: true
        autodelete: false
    player:
      exchange:
        name: TEAMBUILTING.E.PLAYER
        durable: true
        autodelete: false
      queue:
        name: TEAMBUILTING.Q.STATISTIC.PLAYER
        binding: player.#
        durable: true
        autodelete: false

---

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/statisticChangeset.xml
  contexts: default

---

spring:
  profiles: production
  rabbitmq:
      username: ${RABBITMQ_USERNAME}
      virtual-host: ${RABBITMQ_VIRTUAL_HOST}
      password: ${RABBITMQ_PASSWORD}
      host: ${RABBITMQ_HOST}

---

spring:
  profiles: development
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672