info:
  name: teambuiltingstatistic
  description: Team Builting Statistics

server:
  port: ${PORT:8081}

spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      org.hibernate.envers.store_data_at_delete: true
      org.hibernate.envers.global_with_modified_flag: true
      org.hibernate.envers.track_entities_changed_in_revision: true
  datasource:
    initialize: false
    url: jdbc:mysql://mysql:3306/statisticdb?createDatabaseIfNotExist=true
    username: root
    password:
    hikari:
      minimumIdle: 20
      maximumPoolSize: 30
      idleTimeout: 10000
      driverClassName: com.mysql.jdbc.Driver
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jackson:
    serialization:
      write-dates-with-zone-id: false
    deserialization:
      accept-float-as-int: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ


---

# Queue configuration
messaging:
  event.amqp:
    exchange: teambuilting.ex
    queue: teambuilting.queue
    team-event-routing-key: team.event
    player-visited-routing-key: player.visited
    player-deleted-routing-key: player.deleted

---

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/statisticChangeset.xml
  contexts: default

---

spring:
  profiles: production
  datasource:
      url: ${MYSQL_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
  rabbitmq:
      username: ${RABBITMQ_USERNAME}
      virtual-host: ${RABBITMQ_VIRTUAL_HOST}
      password: ${RABBITMQ_PASSWORD}
      host: ${RABBITMQ_HOST}

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/statisticdb?createDatabaseIfNotExist=true
    username: root
    password: root
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672